### ISSUE TITLE
Start the counter later?

### ISSUE THREAD

**Issue by escobar5** [Kerumen/react-native-counter#4]
Is there a way to start the counter after some time, for example, I need to counters, the first one starts immediately, the second one after the first has completed. Is there any way to achieve that?

**Comment by Kerumen** [comment]
Currently, there is no way to achieve that with the current props. If you wanna send a PR for this, I would be happy to review it.
For now you can workaround by mounting the second counter when the first one is completed:

```
class Example extends Component {
  state = { secondCounter: false };
  render() {
    const { secondCounter } = this.state;
    return (
      <View>
        <Counter end={10} onComplete={() => this.setState({ secondCounter: true })} />
        {secondCounter && <Counter end={20} onComplete={this.startSecondCounter} />}
      </View>
    );
  }
}
```
